# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('invitacion_enviada', models.BooleanField(default=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('confirmado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
