# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casamiento', '0003_parejafamilia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parejafamilia',
            name='invitado',
        ),
        migrations.AddField(
            model_name='parejafamilia',
            name='invitado',
            field=models.ManyToManyField(to='casamiento.Invitado'),
        ),
    ]
