# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casamiento', '0007_invitado_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casamiento.Invitado')),
            ],
        ),
    ]
